# Generated by Django 5.2.8 on 2025-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Approved reviews are visible to public'),
        ),
    ]
